"""Generate the router's declarative artifacts from a parsed ``config.toml``.

All transforms are pure Python f-string composition. The writers are
independent so each consuming recipe (futro-network-conf, base-files,
futro-ap-certs) only pays for what it ships.
"""

from __future__ import annotations

import os
from pathlib import Path

from .config import Host, NetworkConfig


# ---- /etc/systemd/network/30-br-{lan,iot}.network.d/10-static-leases.conf


def write_network_dropins(cfg: NetworkConfig, out_dir: Path) -> None:
    """Emit per-bridge ``[DHCPServerStaticLease]`` drop-ins.

    out_dir is the systemd network directory (typically
    ``${D}/etc/systemd/network``). Hosts without a ``mac`` are skipped:
    no MAC, no DHCP reservation possible.
    """

    for vlan, bridge in (("lan", "br-lan"), ("iot", "br-iot")):
        leased = [h for h in cfg.hosts_by_vlan(vlan) if h.mac is not None]
        target = out_dir / f"30-{bridge}.network.d" / "10-static-leases.conf"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_render_lease_dropin(bridge, leased), encoding="utf-8")
        os.chmod(target, 0o644)


def _render_lease_dropin(bridge: str, hosts: list[Host]) -> str:
    header = (
        f"# Generated by routerbuild from config.toml — do not edit by hand.\n"
        f"# Static DHCPv4 reservations for clients on {bridge}.\n"
    )
    if not hosts:
        return header + "# (no static leases declared for this VLAN)\n"
    blocks = [
        f"\n[DHCPServerStaticLease]\n"
        f"# {h.name}\n"
        f"MACAddress={h.mac}\n"
        f"Address={h.ipv4}\n"
        for h in hosts
    ]
    return header + "".join(blocks)


# ---- /etc/systemd/resolved.conf.d/local-zone.conf ---------------------


def write_resolved_dropin(cfg: NetworkConfig, out_dir: Path) -> None:
    """Emit a resolved drop-in pinning ``ReadEtcHosts=yes``.

    out_dir is ``${D}/etc/systemd/resolved.conf.d``. Resolved's stub
    listener (configured separately in resolved-router.conf) serves
    LAN/IoT clients; with ReadEtcHosts on, the generated ``/etc/hosts``
    becomes the LAN DNS source automatically.
    """

    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / "local-zone.conf"
    domain = cfg.router.dns_search_domain
    target.write_text(
        f"# Generated by routerbuild from config.toml — do not edit by hand.\n"
        f"# /etc/hosts is the LAN DNS authority for the .{domain} zone;\n"
        f"# resolved consults it for queries arriving on the stub listeners.\n"
        f"[Resolve]\n"
        f"ReadEtcHosts=yes\n",
        encoding="utf-8",
    )
    os.chmod(target, 0o644)


# ---- /etc/hosts -------------------------------------------------------


def write_etc_hosts(cfg: NetworkConfig, out_path: Path) -> None:
    """Write the full ``/etc/hosts`` file for the router rootfs.

    Every declared host gets ``<ipv4> <name>.<domain> <name> <aliases...>``
    so both bare-name and FQDN lookups resolve. The router's own LAN
    address gets the ``router`` short name.
    """

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(_render_etc_hosts(cfg), encoding="utf-8")
    os.chmod(out_path, 0o644)


def _render_etc_hosts(cfg: NetworkConfig) -> str:
    domain = cfg.router.dns_search_domain
    lines = [
        "# Generated by routerbuild from config.toml — do not edit by hand.",
        "127.0.0.1\tlocalhost",
        "::1\t\tlocalhost ip6-localhost ip6-loopback",
        "ff02::1\t\tip6-allnodes",
        "ff02::2\t\tip6-allrouters",
        "",
        f"# Router self — reachable as `router` / `router.{domain}` on the LAN.",
        f"{cfg.router.lan_ipv4}\trouter.{domain} router",
        f"{cfg.router.iot_ipv4}\trouter.{domain} router",
        "",
        "# Declared hosts.",
        "#",
        "# APs with `cert = true` also carry their public certificate FQDN",
        "# (<label>.<acme domain>) so the LuCI HTTPS name resolves to the AP's",
        "# LAN address. These A records are deliberately local-only: the public",
        "# OVH zone holds nothing but the transient _acme-challenge TXT records.",
    ]
    # APs first, then ordinary devices — infrastructure at the top.
    for a in cfg.aps:
        names = [f"{a.hostname}.{domain}", a.hostname, a.label, *a.aliases]
        if a.cert:
            names.append(a.cert_fqdn(cfg.acme))
        lines.append(f"{a.ipv4}\t{' '.join(names)}")
    for h in cfg.hosts:
        names = [f"{h.name}.{domain}", h.name, *h.aliases]
        lines.append(f"{h.ipv4}\t{' '.join(names)}")
    return "\n".join(lines) + "\n"


# ---- /etc/futro-ap-certs/aps.list -------------------------------------


def write_ap_cert_list(cfg: NetworkConfig, out_path: Path) -> None:
    """Emit the manifest driving the router's ACME issue-and-push loop.

    One whitespace-separated ``<name> <fqdn> <ipv4>`` record per AP, so
    the runtime shell script can consume it with a bare ``while read``
    and no parser. ``<name>`` keys the baked CSR at
    ``/etc/futro-ap-certs/csr/<name>.csr``.
    """

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(_render_ap_cert_list(cfg), encoding="utf-8")
    os.chmod(out_path, 0o644)


def _render_ap_cert_list(cfg: NetworkConfig) -> str:
    lines = [
        "# Generated by routerbuild from config.toml — do not edit by hand.",
        "# <name> <cert-fqdn> <ipv4>",
    ]
    for a in cfg.cert_aps():
        lines.append(f"{a.hostname}\t{a.cert_fqdn(cfg.acme)}\t{a.ipv4}")
    return "\n".join(lines) + "\n"
