[system]
compatible=futro-s920 home router
bootloader=barebox
bundle-formats=-plain

[keyring]
path=/etc/rauc/ca.cert.pem

[slot.rootfs.0]
device=/dev/disk/by-partuuid/f7200003-a001-4000-8001-000000000003
type=ext4
bootname=system0

[slot.rootfs.1]
device=/dev/disk/by-partuuid/f7200004-a001-4000-8001-000000000004
type=ext4
bootname=system1
