#!/bin/sh
#
# Issue (or renew) one Let's Encrypt certificate per OpenWrt AP and push
# the result to the AP.
#
# Why this shape:
#   * DNS-01 is the only viable challenge — the APs sit on RFC1918
#     addresses with no inbound path from the internet — and it needs
#     zone-wide OVH credentials, which is exactly why issuance is
#     centralised here rather than run on each AP.
#   * lego is driven with --csr: the CSR is baked into the AP's image and
#     copied here at build time, so the matching *private key never
#     leaves the AP*. We only ever handle the CSR and the signed cert,
#     both of which are public.
#   * The push is attempted unconditionally on every run, not just after
#     a renewal. The AP-side receiver is idempotent (it only rewrites and
#     restarts uhttpd when the cert actually differs), so an unconditional
#     push costs one cheap SSH round-trip and makes the whole thing
#     self-healing: a `sysupgrade -n` reverts the AP to its baked
#     bootstrap cert, and the next timer tick puts the real one back
#     instead of waiting up to 60 days for the renewal window.
#
# Exit status: non-zero if *any* AP failed, but every AP is attempted —
# one unreachable AP must not block certificate renewal for the others.

set -u

CONF_DIR=/etc/futro-ap-certs
LEGO_PATH=/var/lib/lego
APS_LIST="$CONF_DIR/aps.list"
CSR_DIR="$CONF_DIR/csr"
PUSH_KEY="$CONF_DIR/ap-push-key"

# Set from the generated aps.list header at build time.
ACME_EMAIL="${ACME_EMAIL:?ACME_EMAIL not set (expected from the systemd unit)}"

rc=0

log() { echo "$*"; }
err() { echo "$*" >&2; }

# OVH credentials arrive via EnvironmentFile=/etc/futro-ap-certs/ovh.env.
# Fail loudly rather than letting lego emit a confusing provider error.
for v in OVH_ENDPOINT OVH_APPLICATION_KEY OVH_APPLICATION_SECRET OVH_CONSUMER_KEY; do
    eval "val=\${$v:-}"
    if [ -z "$val" ]; then
        err "Missing $v — populate $CONF_DIR/ovh.env (see files/secrets/README.md)"
        exit 1
    fi
done

if [ ! -r "$APS_LIST" ]; then
    err "Missing $APS_LIST"
    exit 1
fi

# `lego run` in v5 is unified: it obtains when no certificate resource
# exists yet and renews when one does (using a dynamic renewal window of
# 1/3 of the certificate lifetime), so a single invocation covers both
# the first issue and every subsequent renewal.
issue() {
    name="$1"
    csr="$CSR_DIR/$name.csr"

    if [ ! -r "$csr" ]; then
        err "$name: missing CSR at $csr"
        return 1
    fi

    # Every flag below belongs to the `run` subcommand — in lego v5 the
    # only *global* options are --log.*/--config, so a flag placed before
    # `run` is a parse error, not a tolerated alternative spelling.
    #
    # stdin is the aps.list being consumed by the loop below — keep lego
    # away from it so a stray read can't swallow the remaining APs.
    lego run \
        --accept-tos \
        --email "$ACME_EMAIL" \
        --path "$LEGO_PATH" \
        --dns ovh \
        --csr "$csr" < /dev/null
}

# The certificate is public material, so the channel only needs
# integrity+authenticity, not secrecy — but we still pin the AP's host
# key so a spoofed AP can't harvest an admin SSH connection. The keys
# come from /etc/ssh/ssh_known_hosts (openssh's default
# GlobalKnownHostsFile), generated by this recipe from the baked dropbear
# host keys. UserKnownHostsFile=/dev/null makes the system-wide database
# the *only* source of truth: no TOFU accumulation, and no dependence on
# root's ~/.ssh, which ProtectHome=yes hides from this unit anyway.
# The remote end is locked to a forced command by authorized_keys, so
# this key cannot get a shell even if it leaked.
push() {
    name="$1"
    fqdn="$2"
    ip="$3"
    crt="$LEGO_PATH/certificates/$fqdn.crt"

    if [ ! -r "$crt" ]; then
        err "$name: no certificate at $crt — nothing to push"
        return 1
    fi

    # NB: no `ssh -n` here — the certificate is delivered *on stdin*, and
    # -n would redirect stdin from /dev/null and silently push nothing.
    ssh -q \
        -i "$PUSH_KEY" \
        -o IdentitiesOnly=yes \
        -o UserKnownHostsFile=/dev/null \
        -o StrictHostKeyChecking=yes \
        -o BatchMode=yes \
        -o ConnectTimeout=10 \
        "root@$ip" < "$crt"
}

# Field-split on whitespace; skip comments and blank lines.
while read -r name fqdn ip _rest; do
    case "$name" in
        ''|\#*) continue ;;
    esac
    [ -n "${fqdn:-}" ] && [ -n "${ip:-}" ] || continue

    log "=== $name ($fqdn -> $ip)"

    if ! issue "$name"; then
        err "$name: certificate issue/renew failed"
        rc=1
        # Still try to push: a previously-issued cert may simply not have
        # reached the AP yet (e.g. it was offline, or was just reflashed).
    fi

    if ! push "$name" "$fqdn" "$ip"; then
        err "$name: push failed"
        rc=1
    fi
done < "$APS_LIST"

exit "$rc"
